name: Kubernetes HA Cluster Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-k8s-ha:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and upgrade packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install virtualization dependencies if not present
        run: |
          PACKAGES="bridge-utils qemu-kvm virtinst libvirt-dev libvirt-daemon virt-manager"
          TO_INSTALL=""
          for pkg in $PACKAGES; do
            if ! dpkg -l | grep -q $pkg; then
              TO_INSTALL="$TO_INSTALL $pkg"
            fi
          done
          if [ ! -z "$TO_INSTALL" ]; then
            sudo apt install -y $TO_INSTALL
          else
            echo "Virtualization dependencies already installed. Skipping."
          fi

      - name: Check KVM support
        run: kvm-ok

      - name: Install Vagrant if not present
        run: |
          if ! command -v vagrant &> /dev/null; then
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update
            sudo apt install -y vagrant
            vagrant plugin install vagrant-libvirt vagrant-disksize vagrant-vbguest
          else
            echo "Vagrant already installed. Skipping."
          fi

      - name: Install Ansible if not present
        run: |
          if ! command -v ansible &> /dev/null; then
            sudo apt install -y software-properties-common
            sudo apt-add-repository --yes --update ppa:ansible/ansible
            sudo apt install -y ansible python3-passlib
          else
            echo "Ansible already installed. Skipping."
          fi

      - name: Generate SSH keys if not present
        run: |
          if [ ! -f ansible/vagrant ] || [ ! -f ansible/vagrant.pub ]; then
            ssh-keygen -t rsa -b 4096 -f ansible/vagrant -N ""
            chmod 600 ansible/vagrant
            chmod 644 ansible/vagrant.pub
          else
            echo "SSH keys already exist. Skipping generation."
          fi

      - name: Run make install
        run: make install

      - name: Run make up (provision VMs)
        run: make up

      - name: Clear known hosts (if necessary)
        run: |
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.51 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.52 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.101 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.102 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.103 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.201 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.202 || true
          ssh-keygen -f $HOME/.ssh/known_hosts -R 172.16.16.203 || true

      - name: Run make cluster (setup Kubernetes cluster)
        run: make cluster

      - name: Install kubectl if not present
        run: |
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          else
            echo "kubectl already installed. Skipping."
          fi

      - name: Verify cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy test nginx
        run: |
          kubectl create deployment nginx-deployment --image=cgr.dev/chainguard/nginx:latest
          kubectl expose deployment nginx-deployment --port=8080 --target-port=80
          kubectl get pods -o wide
          kubectl get services

      - name: Cleanup test deployment
        if: always()
        run: |
          kubectl delete service nginx-deployment || true
          kubectl delete deployment nginx-deployment || true
